-- First, create a default host user for CSV imported spaces
INSERT INTO users (id, email, name, role, created_at)
VALUES ('csv-import-host', 'host@parkpal.com', 'CSV Import Host', 'host', NOW())
ON CONFLICT (id) DO NOTHING;

-- Clear existing spaces (optional - remove this line if you want to keep existing data)
-- DELETE FROM spaces WHERE host_id = 'csv-import-host';

-- Note: The actual INSERT statements for spaces will be generated by the import script
-- This is just a template. You'll need to run the import script first to get the actual data.

-- Example of what the INSERT would look like:
-- INSERT INTO spaces (
--   host_id, title, location, features, is_available, description, 
--   price_per_day, available_from, available_to, image_url, address, 
--   postcode, latitude, longitude, what3words, available_days, available_hours
-- ) VALUES 
-- ('csv-import-host', 'Sample Space', 'London', 'Secure,Covered', true, 'Great parking space', 
--  15.00, '2024-01-01', '2024-12-31', null, '123 Main St', 'SE17 1AB', 
--  51.4975, -0.1357, 'word.word.word', 'Mon,Tue,Wed,Thu,Fri,Sat,Sun', '00:00-23:59');
